name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release --no-restore
    - name: Build (Unity)
      run: dotnet build --no-restore --configuration Release-Unity --no-restore
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: BeatSaverSharp
        path: BeatSaverSharp/bin/Release/netstandard2.0
    - name: Upload (Unity)
      uses: actions/upload-artifact@v2
      with:
        name: BeatSaverSharp
        path: BeatSaverSharp/bin/Release-Unity/netstandard2.0
